### ISSUE TITLE
Package is not available for 7.7.9 and 7.7.10

### ISSUE THREAD

**Issue by dawoe** [kedde/Our.Umbraco.Community.Tests#1]
Hi,

The package isn't available for these versions. If I look at the appveyor build it seems that a invalid nuget api key is the cause

Dave

**Comment by kedde** [comment]
Hi

Thanks for letting me know. I'll have a look as soon as possible. 

kedde

**Comment by kedde** [comment]
I fixed the issue with the api key and 7.7.10 is now on the nuget gallery
