### ISSUE TITLE
Our.Umbraco.Community.Tests causes missing “Culture and Hostnames” menu Item in Umbraco contextmenu

### ISSUE THREAD

**Issue by terryclancy** [kedde/Our.Umbraco.Community.Tests#2]
Dear Our.Umbraco.Community.Tests  Folk,

As detailed at :
https://stackoverflow.com/questions/29756510/missing-culture-and-hostnames-menuitem-in-umbraco-contextmenu/29756511#29756511
use of Our.Umbraco.Community.Tests and the related Umbraco.Tests.dll when unit testing, results in the “Culture and Hostnames” missing as a menu Item in Umbraco contextmenu.
As described at that locaton:

```
When checking the permissions for a user the users default-permissions are fetched from the database as a string of chars; E.g. the admin users default-permissions are: CADMOSKTPIURZ:5F7

Each letter will allow certain actions(IActions) to be allowed by the user. 

The problem occurred because we had deployed the "Umbraco.Tests.dll" to the environment, which contained an IAction with the same permission-letter as the AssignDomain action ("ActionAssignDomain.cs"). This caused the "Cultures and Hostnames" menu-item to be removed from the resulting menu-item list. 
```

My question is this: given all of the above how exactly should I then resolve this issue (without removing Umbraco.Tests) . I need to modify “Culture and Hostnames”.
Thanks
Terry Clancy
ClanceZ

(Also posted at https://our.umbraco.org/forum/using-umbraco-and-getting-started//91756-umbracotests-causes-missing-culture-and-hostnames-menu-item-in-umbraco-contextmenu )

**Comment by kedde** [comment]
Hi,

If I'm reading this correctly you have put both the test.dll and the umbraco.stuff in the same project. I would create both a "web project"(umbraco project) and "test project" ( this project - has a reference to the web project, and included the test nuget package)
