### ISSUE TITLE
Nuget package not updated for 7.11.x

### ISSUE THREAD

**Issue by dawoe** [kedde/Our.Umbraco.Community.Tests#3]
It seems the package is not updated for 7.11.x

**Comment by dawoe** [comment]
It see also all version after 7.10 are missing as well

**Comment by dawoe** [comment]
I see you work of master-v7 branch. But that hasn't been updated since 7.10 anymore.

Maybe get in touch with Sebastiaan Janssen to see if they changed there branching strategy.

Dave

**Comment by kedde** [comment]
Hi Dave

I'll hope to give it a look in the upcoming week.

**Comment by kedde** [comment]
Hi Dave 

I have now switched to the "cake build"-system - and managed to upload the missing packages. I might need a to tweak a few settings in AppVeyor - but I'll have a look when the next version is released. 

[see the NuGet feed](https://www.nuget.org/packages/Our.Umbraco.Community.Tests/)

Christian

**Comment by kedde** [comment]
7.12.0 is now released 
https://www.nuget.org/packages/Our.Umbraco.Community.Tests/
