### ISSUE TITLE
V8 version

### ISSUE THREAD

**Issue by dawoe** [kedde/Our.Umbraco.Community.Tests#4]
Hi,

Are you planning to release a V8 versions as well ?

Dave

**Comment by kedde** [comment]
Hi

I could do that yes, hopefully I can find some time to do it for V8 releases as well.

**Comment by kedde** [comment]
Hopefully a Our.Umbraco.Community.Tests v8 nuget  package will be avalabel soon: 

I got a mail from NuGet/Microsoft: 

"It is taking longer than expected for your package Our.Umbraco.Community.Tests 8.0.0 to get published. We are looking into it and there is no action on you at this time. We’ll send you an email notification when your package has been published.
Thank you for your patience."

--Kedde

**Comment by dawoe** [comment]
Awesom...looking forward to it

**Comment by kedde** [comment]
https://www.nuget.org/packages/Our.Umbraco.Community.Tests/    Moe has V8 så well
